# Changes here will be overwritten by Copier.
_commit: 598247d
_src_path: gh:Bullish-Design/templateer
author_email: BullishDesignLLC@gmail.com
author_fullname: Bullish Design
author_username: Bullish-Design
copyright_date: '2025'
copyright_holder: Bullish Design
copyright_holder_email: BullishDesignLLC@gmail.com
copyright_license: ISC
insiders: false
project_description: Mini template generation with LLM enhancement
project_name: Templateer2
python_package_command_line_name: templateer2
python_package_distribution_name: templateer2
python_package_import_name: templateer2
repository_name: templateer2
repository_namespace: Bullish-Design
repository_provider: github.com

